Resolve softmax issues with pytorch_model.py
understandable-machine-intelligence-lab/Quantus pull request #283
Opened 2023-07-07 21:11 UTC by dilyabareeva

### Description
- Extraction of softmax layer from pytorch models sometimes lead to problem.
- We want to update the logic of softmax adjustment as follows:
![IMG_4F0CB8FDD9CB-1-1](https://github.com/understandable-machine-intelligence-lab/Quantus/assets/44092813/7e339655-a458-4994-89d2-6208b3252397)

### Implemented changes
  - [ ] Updated logic for softmax adjustments in the model depending on the model structure
  - [ ] The 6 different cases from the photo represented in get_softmax_arg_model method (see comments)
  - [ ] A better way to extract Softmax layer from model by replacing it with Identity (instead of rebuilding the model and forward function)

2023-07-13 08:54 UTC, annahedstroem requested changes
A few things! Thanks @dilyabareeva !

2023-07-16 15:26 UTC, aaarrti commented on quantus/helpers/model/pytorch_model.py
> +        for attr_tpl in list(linear_model.named_modules())[::-1]:
What does `attr_tpl` stand for? 
Please either use a more verbose self-descriptive variable name, or leave a comment on what does it mean.

2023-07-16 15:33 UTC, aaarrti commented
We are modifying the structure of the model provided by the user, it would be great to make it visible to the user what exactly is being done under the hood, and what assumptions were made. 
E.g., for the case when the last softmax layer is replaced by a linear one, we could log a message: 
```
<XAI method name> reuires model with linear top, but found softmax activation on top for <model name>. Removed <layer name> at <layer index>
```

This must not be a warning, since this is expected behaviour. I'd suggest using `logging.info`, and set log format to something like `"[%(filename)s:%(lineno)s->%(funcName)s()]:%(levelname)s: %(message)s"`, so the user can see where it is coming from.

2023-07-21 18:20 UTC, dilyabareeva commented on quantus/helpers/model/pytorch_model.py
>  # Quantus is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser Gen
Both use the same ModelInterface - so the public methods are the same. The logic in tf_model might need to be changed similarly: I'm not 100% sure that model.layers[-1] reliably returns the actual output layer in tensorflow. But this PR is about PyTorch, so maybe this is worth opening another issue to further investigate.

2023-07-21 18:40 UTC, dilyabareeva commented on quantus/helpers/model/pytorch_model.py
> -    @cachedmethod(operator.attrgetter("cache"))
We changed the method in a way that we create a deepcopy of a model before we replace Softmax with Identity (we don't want to meddle with the original model of the user, and only want to create a non-softmax copy for metric calculations). The cachedmethod attributor seems to have problems with persisting very large objects like pytorch model, but the lru_cache seems to be working fine. See also https://docs.python.org/3/faq/programming.html#faq-cache-method-calls.

2023-08-28 08:36 UTC, annahedstroem reviewed
OK.

2023-08-29 07:01 UTC, merged